baseURL = "https://hyuk-dev.github.io/"
title = "Hyuk Tech"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Hyuk Tech"
description = "ì´ë™í˜ ê¸°ìˆ  ë¸”ë¡œê·¸"
keywords = [ "Blog", "Portfolio", "Backend", "ê¸°ìˆ ", "ë¸”ë¡œê·¸" ]
author = "Lee"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

# mainsections = ["page", "post", "archive", "search"]


[params.assets]
favicon = "./img/favicons/favicon.ico"
favicon16x16 = "./img/favicons/favicon16x16.png"
favicon32x32 = "./img/favicons/favicon32x32.png"
apple_touch_icon = "./img/favicons/apple_touch_icon.png"
disableFingerprinting = true

[params.label]
text = "Hyuk Tech"
icon = "./img/favicons/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "ì•ˆë…•í•˜ì„¸ìš”!ğŸ‘‹"
Content = "ì €ì˜ ê¸°ìˆ  ë¸”ë¡œê·¸ì— ì™€ì£¼ì…”ì„œ ê°ì‚¬í•©ë‹ˆë‹¤."

#   [[params.socialIcons]]
#   name = "twitter"
#   url = "https://twitter.com/"

#   [[params.socialIcons]]
#   name = "stackoverflow"
#   url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hyuk-dev"

#   [params.analytics.google]
#   SiteVerificationTag = "XYZabc"

#   [params.analytics.bing]
#   SiteVerificationTag = "XYZabc"

#   [params.analytics.yandex]
#   SiteVerificationTag = "XYZabc"

#   [params.cover]
#   hidden = true
#   hiddenInList = true
#   hiddenInSingle = true

[params.editPost]
URL = "https://github.com/hyuk-dev/blog/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

#   [params.fuseOpts]
#   isCaseSensitive = false
#   shouldSort = true
#   location = 0
#   distance = 1_000
#   threshold = 0.4
#   minMatchCharLength = 0
#   keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archives"
name = "ì•„ì¹´ì´ë¸Œ"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "íƒœê·¸"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "portfolio"
name = "í¬íŠ¸í´ë¦¬ì˜¤"
url = "https://hyuk.dev"
weight = 30

[[menu.main]]
identifier = "search"
name = "ê²€ìƒ‰"
url = "/search/"
weight = 40

[markup.highlight]
noClasses = false